#!/bin/sh

set -eu

cd "$(dirname "$0")"

mkdir -p ca/out

USER_NAME="${USER:-$(id -un)}"

docker build --tag self-sign-cert-ca -f ca/Dockerfile . \
  --build-arg USER_UID="$(id -u)" \
  --build-arg USER_GID="$(id -g)" \
  --build-arg USER_NAME="$USER_NAME"

docker run --rm \
  -u "$(id -u):$(id -g)" \
  -v "$PWD/ca/out:/out" \
  -e CANAME="$1" \
  self-sign-cert-ca

exit 0

